version: "3.3"
services:
  jenkins-docker:
    image: docker:20.10.10-dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
    - "2376"
    volumes:
    - jenkins-data:/var/jenkins_home
    - jenkins-docker-certs:/certs/client
  jenkins:
    build: ./
    container_name: jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
    - "8080"
    - "50000"
    volumes:
    - jenkins-data:/var/jenkins_home
    - jenkins-docker-certs:/certs/client:ro

volumes:
  jenkins-data:
  jenkins-docker-certs:

